# Generated by Django 5.0.4 on 2024-04-30 14:15

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_product_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='product_title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='product_desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
